Eric's Awesome Website
author: Eric Smith
email: esmith1092@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Eric's Website is safe happy space with only good vibes and cool people

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  esmith1092 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
